import { ChangeDetectionStrategy, Component } from "@angular/core";
import { InputComponent } from "../../shared/ui-components/atoms/input/input.component";
import { BridgesInputType } from "../../shared/ui-components/atoms/input/enum/bridges-input-type.enum";
import { SelectComponent } from "../../shared/ui-components/atoms/select/select.component";
import { DropdownOptionsModel } from "../../shared/ui-components/atoms/select/select.model";
import { FormsModule } from "@angular/forms";
import { MatButtonModule } from "@angular/material/button";
import { MatDividerModule } from "@angular/material/divider";
import { MatIconModule } from "@angular/material/icon";

@Component({
  selector: "app-ui-playground",
  imports: [
    InputComponent,
    SelectComponent,
    MatIconModule,
    MatDividerModule,
    MatButtonModule,
    FormsModule,
  ],
  templateUrl: "./ui-playground.component.html",
  styleUrl: "./ui-playground.component.scss",
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class UiPlaygroundComponent {
  icons = [
    "icon-eye",
    "icon-account_circle",
    "icon-add_circle",
    "icon-add",
    "icon-archive",
    "icon-arrow_back",
    "icon-arrow_drop_down",
    "icon-arrow_drop_up",
    "icon-arrow_forward",
    "icon-arrow_left",
    "icon-arrow_right",
    "icon-attach_file",
    "icon-bookedsessions",
    "icon-bookmark_filled",
    "icon-bookmark",
    "icon-cancel",
    "icon-chat_bubble-1",
    "icon-chat_bubble",
    "icon-check_box_outline_blank",
    "icon-check_box-1",
    "icon-check_box",
    "icon-check_indeterminate_small",
    "icon-check_small",
    "icon-check",
    "icon-close",
    "icon-commute",
    "icon-content_cut",
    "icon-currency_pound",
    "icon-dark_mode",
    "icon-dashboard_2",
    "icon-delete",
    "icon-directions_bus",
    "icon-directions_car",
    "icon-directions_subway",
    "icon-directions_walk",
    "icon-Dot",
    "icon-download",
    "icon-edit",
    "icon-error",
    "icon-fast_forward_filled",
    "icon-fast_forward",
    "icon-fast_rewind_filled",
    "icon-fast_rewind",
    "icon-favorite",
    "icon-folder_filled",
    "icon-folder",
    "icon-forward",
    "icon-g_translate",
    "icon-GIF",
    "icon-gmail_groups",
    "icon-home",
    "icon-inbox-1",
    "icon-inbox",
    "icon-indeterminate_check_box-1",
    "icon-indeterminate_check_box",
    "icon-info",
    "icon-keyboard_return",
    "icon-keyboard",
    "icon-language",
    "icon-light_mode",
    "icon-list",
    "icon-local_taxi",
    "icon-location_on-1",
    "icon-location_on",
    "icon-logout",
    "icon-mail-1",
    "icon-mail",
    "icon-menu",
    "icon-mic",
    "icon-mobile_friendly",
    "icon-mood",
    "icon-more_horiz",
    "icon-more_vert",
    "icon-music_note",
    "icon-navigate_before",
    "icon-navigate_down",
    "icon-navigate_next",
    "icon-navigate_up",
    "icon-notifications",
    "icon-outbox",
    "icon-password",
    "icon-patient_list",
    "icon-pause",
    "icon-person",
    "icon-photo",
    "icon-play_arrow_filled",
    "icon-play_arrow",
    "icon-radio_button_checked",
    "icon-radio_button_unchecked",
    "icon-schedule",
    "icon-search",
    "icon-send",
    "icon-settings-1",
    "icon-settings",
    "icon-share",
    "icon-skip_next_filled",
    "icon-skip_next",
    "icon-skip_previous_filled",
    "icon-skip_previous",
    "icon-staff",
    "icon-star_filled",
    "icon-star",
    "icon-stars-1",
    "icon-stars",
    "icon-sticker",
    "icon-text_fields",
    "icon-today",
    "icon-trainer",
    "icon-upload",
    "icon-videocam",
    "icon-visibility_off",
  ];
  selectOptions: DropdownOptionsModel<string>[] = [
    { value: "1", key: "Option 1" },
    { value: "2", key: "Option 2" },
    { value: "3", key: "Option 3" },
  ];
  get BridgesInputTypes() {
    return BridgesInputType;
  }
}
